---
dependency:
  name: galaxy

driver:
  name: docker

provisioner:
  name: ansible

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint .

platforms:
  - name: Debian10
    image: geerlingguy/docker-debian10-ansible:latest
    command: ""
    volumes: [ /sys/fs/cgroup:/sys/fs/cgroup:ro ]
    pre_build_image: true
    privileged: true
  - name: Debian11
    image: geerlingguy/docker-debian11-ansible:latest
    command: ""
    volumes: [ /sys/fs/cgroup:/sys/fs/cgroup:ro ]
    pre_build_image: true
    privileged: true

  - name: Ubuntu2004
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    command: ""
    volumes: [ /sys/fs/cgroup:/sys/fs/cgroup:ro ]
    pre_build_image: true
    privileged: true
