---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true

  vars_files:
    - ../../defaults/main.yml

  pre_tasks:
    - name: Check packages
      package_facts:
        manager: auto

  tasks:
    - name: Check if apt packages are installed
      ansible.builtin.assert:
        that: "'{{ terraform_pkg_name }}' in ansible_facts.packages"
